# Generated by Django 5.0 on 2023-12-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
