# Generated by Django 5.0 on 2023-12-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_company_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='Tag',
            new_name='TagPosts',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='tag_posts',
        ),
        migrations.RemoveField(
            model_name='company',
            name='tag',
        ),
        migrations.AddField(
            model_name='company',
            name='tag_rating',
            field=models.ManyToManyField(to='blog.tagrating'),
        ),
    ]
