# Generated by Django 5.0 on 2024-01-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.RemoveField(
            model_name='advantage',
            name='company',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='company',
            name='tag_rating',
        ),
        migrations.RemoveField(
            model_name='securityscore',
            name='company',
        ),
        migrations.RemoveField(
            model_name='teamscore',
            name='company',
        ),
        migrations.RemoveField(
            model_name='productscore',
            name='company',
        ),
        migrations.RemoveField(
            model_name='review',
            name='company',
        ),
        migrations.DeleteModel(
            name='Guides',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tag_posts',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='email',
        ),
        migrations.AlterField(
            model_name='booking',
            name='comment',
            field=models.CharField(max_length=300, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=300, verbose_name='Телефон'),
        ),
        migrations.DeleteModel(
            name='Advantage',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='TagRating',
        ),
        migrations.DeleteModel(
            name='SecurityScore',
        ),
        migrations.DeleteModel(
            name='TeamScore',
        ),
        migrations.DeleteModel(
            name='ProductScore',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='TagPosts',
        ),
    ]
